# Generated by Django 2.1.7 on 2020-02-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Basic Package (No food, No shirt)'), (20, 'Basic Package + food (No shirt)'), (30, 'Basic Package + shirt (No food)'), (40, 'Total Package (Food + Shirt)')], db_index=True, default=10),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
